name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install
      - run: pnpm lint
      - run: npx playwright install --with-deps
      - run: pnpm dlx playwright@1.51.0 install-deps
      # For now, we only need Chromium
      - run: pnpm dlx playwright@1.51.0 install chromium
      - run: pnpm test
      - name: Install linux dependencies
        run: |
          sudo apt-get install --no-install-recommends -y \
          xvfb
      - run: xvfb-run pnpm tonkeeper
        env:
          WALLET_MNEMONIC: ${{ secrets.WALLET_MNEMONIC }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-artifacts
          path: |
            playwright-report/
            test-results/
          retention-days: 10
